// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about-us": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about-us";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./components/core/about-us/about-us.tsx": {
    id: "components/core/about-us/about-us";
    page: "/about-us";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "components/core/about-us/about-us": typeof import("./app/./components/core/about-us/about-us.tsx");
};